#!/usr/bin/env python3
"""Cross-validation vector generator for the gumbel detector port.

Runs the reference Python `detect_gumbel.py` internals (tokenize_simple,
_seed, _uniform, _poisson_survival, detect_token_ids) and emits
`src/gumbel/vectors_gen_test.mbt` with per-case expectations. Floats are
compared with a small relative tolerance because the port computes natural
log via log2(x)*ln2 while Python uses libm log/log1p.
"""

from __future__ import annotations

import random
import sys
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "reference" / "watermarks-remover"))
import detect_gumbel as DG  # noqa: E402


def dbl(x: float) -> str:
    """MoonBit-parseable (no exponent) round-trip decimal for a double."""
    s = repr(float(x))
    if "e" in s or "E" in s:
        s = f"{Decimal(s):f}"
    if "." not in s:
        s = s + ".0"
    return s


def ids_lit(ids: list[int]) -> str:
    inner = ", ".join(f"{i}UL" for i in ids)
    return f"[{inner}]"


def text_lit(s: str) -> str:
    out = ['"']
    for ch in s:
        cp = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 <= cp <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\u{{{cp:X}}}")
    out.append('"')
    return "".join(out)


def main() -> None:
    rng = random.Random(20260822)
    lines = [
        "// Generated by tools/gen_gumbel_vectors.py -- DO NOT EDIT BY HAND.",
        "// Expectations come from the reference Python detect_gumbel.py.",
        "",
        "fn close(a : Double, b : Double) -> Bool {",
        "  let diff = if a > b { a - b } else { b - a }",
        "  let mag = if a > b { a } else { b }",
        "  diff <= mag * 0.000000001 + 0.000000000000001",
        "}",
        "",
        "fn assert_close(label : String, got : Double, want : Double) -> Unit raise {",
        "  if !close(got, want) {",
        "    println(\"mismatch [\" + label + \"]: got=\" + got.to_string() + \" want=\" + want.to_string())",
        "  }",
        "  assert_true(close(got, want), msg=label)",
        "}",
        "",
    ]

    cases: list[dict] = []

    # tokenize_simple parity: mixed scripts and digits
    texts = [
        "The quick brown fox jumps over the lazy dog",
        "Hello, WORLD! 123 abc... 456",
        "中文没有ASCII词只有123数字",
        "  leading   and\ttrailing  ",
        "",
        "MiXeD CaSe WoRdS lower UPPER",
    ]
    for i, t in enumerate(texts):
        cases.append({"name": f"tok-{i}", "kind": "tokenize", "text": t})

    # token-id detection: windows, repeat masking, key shapes
    det_cases = [
        {"name": "ids-short", "ids": [1, 2, 3], "key": "0x00112233445566778899aabbccddeeff", "window": 4},
        {"name": "ids-basic", "ids": [10, 20, 30, 40, 50, 60, 70, 80], "key": "self-hosted key", "window": 4},
        {"name": "ids-window1", "ids": [5, 9, 2, 8, 2, 8, 2, 8], "key": "k", "window": 1},
        {"name": "ids-window8", "ids": list(range(100, 125)), "key": "0xdeadbeef", "window": 8},
        {"name": "ids-repeats", "ids": [7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 7, 7], "key": "repeat-key", "window": 3},
        {"name": "ids-nomask", "ids": [7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 7, 7], "key": "repeat-key", "window": 3, "mask_repeated": False},
        {"name": "ids-big", "ids": [2**64 - 1, 2**63, 42, 0, 2**64 - 2, 1], "key": "boundaries", "window": 2},
    ]
    for i in range(8):
        n = rng.randint(10, 60)
        ids = [rng.getrandbits(64) for _ in range(n)]
        key = rng.choice(["fuzz-key", "0x" + rng.getrandbits(256).to_bytes(32, "big").hex(), "клю́ч"])
        det_cases.append({"name": f"ids-fuzz-{i}", "ids": ids, "key": key, "window": rng.choice([1, 2, 4, 6])})

    # greedy low-uniform construction: a strongly watermarked sequence
    key = "greedy-key"
    H = 4
    ids = [900, 901, 902, 903]
    for _ in range(24):
        seed = DG._seed(DG._normalize_key(key), tuple(ids[-H:]))
        best, best_u = None, 1.1
        for cand in range(1000):
            u = DG._uniform(seed, cand)
            if u < best_u:
                best, best_u = cand, u
        ids.append(best)
    det_cases.append({"name": "ids-greedy", "ids": ids, "key": key, "window": H, "threshold": 1e-6})

    # text detection end-to-end
    text_cases = [
        {"name": "text-basic", "text": "one two three four five six seven eight nine ten", "key": "text-key"},
        {"name": "text-hex", "text": "alpha beta gamma delta epsilon zeta eta theta", "key": "0xA1B2C3D4E5F60718"},
    ]

    for c in cases:
        i = len(lines)
        py_ids = DG.tokenize_simple(c["text"])
        lines.extend(
            [
                f'test "gumbel {c["name"]}" {{',
                f"  let ids = tokenize_simple({text_lit(c['text'])})",
                f"  assert_eq(ids.length(), {len(py_ids)}, msg=\"{c['name']}/count\")",
            ]
        )
        for j, tid in enumerate(py_ids):
            lines.append(f"  assert_true(ids[{j}] == {tid}UL, msg=\"{c['name']}/id{j}\")")
        lines.append("}")
        lines.append("")

    for c in det_cases:
        window = c.get("window", 4)
        threshold = c.get("threshold", 1e-6)
        mask = c.get("mask_repeated", True)
        rep = DG.detect_token_ids(c["ids"], c["key"], window=window, threshold=threshold, mask_repeated=mask)
        # recompute the unrounded statistic the report rounds to 6 decimals
        import math as _m
        _kb = DG._normalize_key(c["key"])
        _seen, _stat = set(), 0.0
        for _t in range(window, len(c["ids"])):
            _win = tuple(c["ids"][_t - window : _t])
            if mask:
                if _win in _seen:
                    continue
                _seen.add(_win)
            _stat += -_m.log1p(-DG._uniform(DG._seed(_kb, _win), c["ids"][_t]))
        rep["statistic"] = _stat
        if rep["counted"] > 0:
            _p = rep["p_value"]
            rep["score"] = -_m.log10(_p) if _p > 0.0 else 300.0
        lines.extend(
            [
                f'test "gumbel {c["name"]}" {{',
                f"  let report = detect_token_ids({ids_lit(c['ids'])}, {text_lit(c['key'])},",
                f"    window={window}, threshold={dbl(threshold)}, mask_repeated={str(mask).lower()})",
                f"  assert_eq(report.counted, {rep['counted']}, msg=\"{c['name']}/counted\")",
                f"  assert_eq(report.tokens_total, {rep['tokens_total']}, msg=\"{c['name']}/total\")",
                f"  assert_eq(report.skipped_repeated, {rep['skipped_repeated']}, msg=\"{c['name']}/skrep\")",
                f"  assert_eq(report.skipped_no_context, {rep['skipped_no_context']}, msg=\"{c['name']}/skctx\")",
                f"  assert_close(\"{c['name']}/stat\", report.statistic, {dbl(rep.get('statistic', 0.0))})",
                f"  assert_close(\"{c['name']}/p\", report.p_value, {dbl(rep.get('p_value', 1.0))})",
                f"  assert_close(\"{c['name']}/score\", report.score, {dbl(rep.get('score', 0.0))})",
                f"  assert_eq(report.is_watermarked, {str(rep['is_watermarked']).lower()}, msg=\"{c['name']}/flag\")",
                "}",
                "",
            ]
        )
        # per-position uniform parity for the first few counted positions
        key_bytes = DG._normalize_key(c["key"])
        emitted = 0
        for t in range(window, len(c["ids"])):
            if emitted >= 3:
                break
            win = tuple(c["ids"][t - window : t])
            u = DG._uniform(DG._seed(key_bytes, win), c["ids"][t])
            lines.extend(
                [
                    f'test "gumbel {c["name"]}-u{t}" {{',
                    f"  let ids = {ids_lit(c['ids'])}",
                    f"  let kb = normalize_key({text_lit(c['key'])})",
                    f"  let u = gumbel_uniform(gumbel_seed(kb, ids, {t - window}, {window}), ids[{t}])",
                    f"  assert_close(\"{c['name']}-u{t}\", u, {dbl(u)})",
                    "}",
                    "",
                ]
            )
            emitted += 1

    for c in text_cases:
        rep = DG.detect_text(c["text"], c["key"])
        import math as _m
        _kb = DG._normalize_key(c["key"])
        _py_ids = DG.tokenize_simple(c["text"])
        _seen, _stat = set(), 0.0
        for _t in range(4, len(_py_ids)):
            _win = tuple(_py_ids[_t - 4 : _t])
            if _win in _seen:
                continue
            _seen.add(_win)
            _stat += -_m.log1p(-DG._uniform(DG._seed(_kb, _win), _py_ids[_t]))
        rep["statistic"] = _stat
        _p = rep["p_value"]
        rep["score"] = -_m.log10(_p) if _p > 0.0 else 300.0
        lines.extend(
            [
                f'test "gumbel {c["name"]}" {{',
                f"  let report = detect_text({text_lit(c['text'])}, {text_lit(c['key'])})",
                f"  assert_eq(report.counted, {rep['counted']}, msg=\"{c['name']}/counted\")",
                f"  assert_close(\"{c['name']}/stat\", report.statistic, {dbl(rep.get('statistic', 0.0))})",
                f"  assert_close(\"{c['name']}/p\", report.p_value, {dbl(rep.get('p_value', 1.0))})",
                "}",
                "",
            ]
        )

    out = ROOT / "src" / "gumbel" / "vectors_gen_wbtest.mbt"
    out.write_text("\n".join(lines), encoding="ascii")
    n_tests = sum(1 for l in lines if l.startswith("test "))
    print(f"wrote {out.relative_to(ROOT)}: {n_tests} tests")


if __name__ == "__main__":
    main()
