// Generate web/string-imports.js from a wasm-gc build that uses
// `imported-string-constants: "_"` (see web/main/moon.pkg): every string
// literal is imported as a global constant named by its own content, from
// module `_`. Browsers that do not auto-provision these constants (the
// non-standard third `compileOptions` argument of WebAssembly.instantiate)
// need an explicit import object, which this script emits.
//
// Usage: node tools/gen_string_imports.mjs <main.wasm> <string-imports.js>
import { readFileSync, writeFileSync } from "node:fs";

const [wasmPath, outPath] = process.argv.slice(2);
if (!wasmPath || !outPath) {
  console.error("usage: node gen_string_imports.mjs <main.wasm> <string-imports.js>");
  process.exit(1);
}

const module = await WebAssembly.compile(readFileSync(wasmPath));
const constants = WebAssembly.Module.imports(module)
  .filter((i) => i.module === "_" && i.kind === "global")
  .map((i) => i.name);

const entries = constants.map((c) => `  ${JSON.stringify(c)}: ${JSON.stringify(c)},\n`);
writeFileSync(
  outPath,
  "// GENERATED by tools/gen_string_imports.mjs — do not edit.\n" +
  "// Imported string constants (module `_`) for the wasm-gc build.\n" +
  `const WASM_STRING_IMPORTS = {\n${entries.join("")}};\n`,
);
console.log(`${outPath}: ${constants.length} string constants`);
