#!/usr/bin/env python3
"""Cross-validation vectors for lexical divergence and candidate selection."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "reference" / "watermarks-remover"))
from rewrite_text import _lexical_divergence, _select_candidate  # noqa: E402


def text_lit(s: str) -> str:
    out = ['"']
    for ch in s:
        cp = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif 0x20 <= cp <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\u{{{cp:X}}}")
    out.append('"')
    return "".join(out)


def dbl(x: float) -> str:
    from decimal import Decimal

    s = repr(float(x))
    if "e" in s or "E" in s:
        s = f"{Decimal(s):f}"
    if "." not in s:
        s = s + ".0"
    return s


PAIRS = [
    ("same text", "the quick brown fox", "the quick brown fox"),
    ("no tokens", "...", "!!!"),
    ("one side empty", "hello world", ""),
    ("synonym swap", "the quick brown fox jumps", "a swift tan fox leaps"),
    ("reordered", "alpha beta gamma delta", "delta gamma beta alpha"),
    ("disjoint", "one two three four", "five six seven eight"),
    ("single token", "hello", "hello"),
    ("cjk mixed", "中文 text with words 123", "中文 other words 456"),
    ("digit change", "version 1.2.3 is out", "version 1.2.4 is out"),
]

SELECTIONS = [
    ("pick diverged", "the quick brown fox", ["the quick brown fox", "a swift tan fox leaps", "the quick brown fox"]),
    ("length guard", "short text here", ["totally different wording everywhere indeed", "short text here"]),
]


def main() -> None:
    lines = [
        "// Generated by tools/gen_rewrite_vectors.py -- DO NOT EDIT BY HAND.",
        "",
        "fn close(a : Double, b : Double) -> Bool {",
        "  let diff = if a > b { a - b } else { b - a }",
        "  let mag = if a > b { a } else { b }",
        "  diff <= mag * 0.000000001 + 0.000000000000001",
        "}",
        "",
    ]
    for name, a, b in PAIRS:
        want = _lexical_divergence(a, b)
        lines.extend(
            [
                f'test "divergence {name}" {{',
                f"  let got = lexical_divergence({text_lit(a)}, {text_lit(b)})",
                f"  assert_true(close(got, {dbl(want)}), msg=\"{name}\")",
                "}",
                "",
            ]
        )
    for name, original, cands in SELECTIONS:
        _, scores = _select_candidate(original, cands)
        best = max(range(len(cands)), key=lambda i: scores[i])
        lines.extend(
            [
                f'test "selection {name}" {{',
                f"  let cands : Array[String] = [{', '.join(text_lit(c) for c in cands)}]",
                f"  let (idx, scores) = select_candidate({text_lit(original)}, cands)",
                f"  assert_eq(idx, {best}, msg=\"{name}/idx\")",
                f"  assert_eq(scores.length(), {len(scores)}, msg=\"{name}/nscores\")",
                "  let want_scores : Array[Double] = [" + ", ".join(dbl(s) for s in scores) + "]",
                "  for i = 0; i < scores.length(); i = i + 1 {",
                f"    assert_true(close(scores[i], want_scores[i]), msg=\"{name}/s\" + i.to_string())",
                "  }",
                "}",
                "",
            ]
        )
    out = ROOT / "src" / "rewrite" / "vectors_gen_test.mbt"
    out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
