#!/usr/bin/env python3
"""Generate src/unicodedata/tables.mbt from CPython's unicodedata.

The MoonBit port of watermarks-remover's Layer A (text_unicode.py) needs three
kinds of Unicode data that MoonBit core does not ship:

  1. the full Cf (format) category        -> `other_cf` catch-all + labels
  2. L / M letter membership restricted to the five script ranges used by
     _joining_script / _is_mongolian_letter / _is_khmer_letter
  3. "U+XXXX NAME (CAT)" labels for every codepoint that can appear as a hit

Codepoints with no name (private-use, noncharacters, reserved ignorables,
unnamed tag chars) are synthesized at runtime in MoonBit as "UNKNOWN (Co|Cn)",
matching Python's `unicodedata.name(ch, "UNKNOWN")` fallback, so they are not
emitted here.

Regenerate after a Unicode bump: rerun this script with the newest CPython.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "reference" / "watermarks-remover"))
import text_unicode as TU  # noqa: E402

MAX_CP = 0x10FFFF
SCRIPT_GROUP_BOUNDS = (0x0600, 0x18AF)  # union of the five _joining_script ranges


def category(cp: int) -> str:
    return unicodedata.category(chr(cp))


def ranges_of(pred, lo: int, hi: int) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(lo, hi + 1):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, hi))
    return out


def in_script_groups(cp: int) -> bool:
    for lo, hi in (
        (0x0600, 0x08FF),
        (0x0900, 0x0DFF),
        (0x0F00, 0x109F),
        (0x1780, 0x17FF),
        (0x1800, 0x18AF),
    ):
        if lo <= cp <= hi:
            return True
    return False


def main() -> None:
    cf = ranges_of(lambda cp: category(cp) == "Cf", 0, MAX_CP)
    letters = ranges_of(
        lambda cp: in_script_groups(cp) and category(cp)[0] == "L", *SCRIPT_GROUP_BOUNDS
    )
    marks = ranges_of(
        lambda cp: in_script_groups(cp) and category(cp)[0] == "M", *SCRIPT_GROUP_BOUNDS
    )

    label_cps: set[int] = set()
    label_cps |= set(TU.STRIP_CODEPOINTS)
    label_cps |= set(TU.SPACE_HOMOGLYPHS)
    label_cps |= set(TU.LATIN_CONFUSABLES)
    label_cps |= set(TU.EMOJI_GLUE_CODEPOINTS)
    label_cps |= set(range(0xE0100, 0xE01F0))  # VS17-VS256
    label_cps |= set(range(0xE0001, 0xE0080))  # tag characters
    label_cps |= {cp for cp in range(MAX_CP + 1) if category(cp) == "Cf"}

    labels: list[tuple[int, str]] = []
    synthesized = 0
    for cp in sorted(label_cps):
        if TU._is_private_use(cp):
            synthesized += 1
            continue
        try:
            name = unicodedata.name(chr(cp))
        except ValueError:
            synthesized += 1  # noncharacter / reserved ignorable / unnamed tag char
            continue
        labels.append((cp, f"U+{cp:04X} {name} ({category(cp)})"))

    def cp_set_ranges(cps) -> list[tuple[int, int]]:
        return ranges_of(lambda cp: cp in cps, min(cps), max(cps))

    def emit_ranges(name: str, cps) -> None:
        lines.append("///|")
        lines.append(f"let {name} : Array[(Int, Int)] = [")
        lines.extend(f"  (0x{a:04X}, 0x{b:04X})," for a, b in cp_set_ranges(cps))
        lines.append("]")
        lines.append("")

    def emit_cp_map(name: str, mapping: dict[int, str]) -> None:
        lines.append("///|")
        lines.append(f"let {name} : Array[(Int, String)] = [")
        lines.extend(f'  (0x{cp:04X}, "{text}"),' for cp, text in sorted(mapping.items()))
        lines.append("]")
        lines.append("")

    lines = [
        "// Generated by tools/gen_unicode_tables.py — DO NOT EDIT BY HAND.",
        f"// Source: CPython {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
        f" unicodedata (Unicode {unicodedata.unidata_version}),",
        "// tables mirrored from watermarks-remover text_unicode.py.",
        "",
    ]
    lines.append("///|")
    lines.append("let cf_ranges : Array[(Int, Int)] = [")
    lines.extend(f"  (0x{a:04X}, 0x{b:04X})," for a, b in cf)
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let script_letter_ranges : Array[(Int, Int)] = [")
    lines.extend(f"  (0x{a:04X}, 0x{b:04X})," for a, b in letters)
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let script_mark_ranges : Array[(Int, Int)] = [")
    lines.extend(f"  (0x{a:04X}, 0x{b:04X})," for a, b in marks)
    lines.append("]")
    lines.append("")

    # Layer A sets mirrored from text_unicode.py
    emit_ranges("strip_cps", TU.STRIP_CODEPOINTS)
    emit_cp_map("space_homoglyphs", TU.SPACE_HOMOGLYPHS)
    emit_cp_map("latin_confusables", TU.LATIN_CONFUSABLES)
    emit_ranges("bidi_cps", TU._BIDI_CPS)
    emit_ranges("preservable_bidi_cps", TU._PRESERVABLE_BIDI_CPS)
    emit_ranges("zw_family", TU._ZW_FAMILY)
    emit_ranges("emoji_glue_cps", TU.EMOJI_GLUE_CODEPOINTS)
    emit_ranges("script_joiners", TU._SCRIPT_JOINERS)
    emit_ranges("orthographic_cf", TU._ORTHOGRAPHIC_CF)
    emit_ranges("mongolian_fvs", TU._MONGOLIAN_FVS)
    emit_ranges("khmer_vowels", TU._KHMER_VOWELS)
    emit_ranges("hangul_fillers", TU._HANGUL_FILLERS)

    lines.append("///|")
    lines.append("let layout_cf_controls : Array[(Int, Int, Int, Int)] = [")
    for controls, script in TU._LAYOUT_CF_CONTROLS:
        lines.append(f"  (0x{controls.start:04X}, 0x{controls.stop - 1:04X},"
                     f" 0x{script.start:05X}, 0x{script.stop - 1:05X}),")
    lines.append("]")
    lines.append("")

    lines.append("///|")
    lines.append("let label_pairs : Array[(Int, String)] = [")
    lines.extend(f'  (0x{cp:04X}, "{text}"),' for cp, text in labels)
    lines.append("]")
    lines.append("")

    out = ROOT / "src" / "unicodedata" / "tables.mbt"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {out.relative_to(ROOT)}: cf_ranges={len(cf)} letter_ranges={len(letters)} "
        f"mark_ranges={len(marks)} labels={len(labels)} synthesized_at_runtime={synthesized}"
    )


if __name__ == "__main__":
    main()
